# Generated by Django 3.0.6 on 2020-05-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
